 #This file verify if hosts file has enough information or not according to your choice such as dns/proxy/internal_repo.

 - name: Checking conditions for configurations
   hosts: localhost
   gather_facts: no

   tasks:
   - name: Verify if it gets enough information for selected options(dns/proxy/internal_repo)
     set_fact:
       internet_connected: "{{ hostvars[groups.oo_ose3_install.0].internet_connected }}"
       dns_install: "{{ hostvars[groups.oo_ose3_install.0].dns_install }}"
       proxy_install: "{{ hostvars[groups.oo_ose3_install.0].proxy_install }}"
       internal_repo_install: "{{ hostvars[groups.oo_ose3_install.0].internal_repo_install }}"
       nfs_iscsi_install: "{{ hostvars[groups.oo_ose3_install.0].nfs_iscsi_install }}"
       master_count: "{{ (groups[g_masters_group] | length) }}"
       subscription_register: "{{ (hostvars[groups.oo_ose3_install.0].subscription_register) }}"
     tags: add_host
   
   - name: Check DNS parameters
     shell: "echo Checking DNS parameters"
     notify:
       - Verify dns_wildcard_domain
       - Verify dns_routers_ip
       - Verify dns_host_ip
     when: "{{dns_install}} == true"
     tags: add_host

   - name: Check Proxy parameters
     shell: "echo Checking Proxy parameters"
     notify:
       - Verify proxy_vip
       - Verify proxy_host_ip
     when: "{{proxy_install}} == true"
     tags: add_host

   - name: Check Internal_repo parameters
     shell: "echo Checking Internal_repo parameters"
     notify:
       - Verify internal_repo_host_ip
       - Verify internal_repo_host_name
     when: "{{internal_repo_install}} == true"
     tags: add_host

   - name: Check NFS  parameters
     shell: "echo Checking NFS parameters"
     notify:
       - Verify nfs_iscsi_host_ip
     when: "{{nfs_iscsi_install}} == true"
     tags: add_host

   - name: Check Master HA parameters with pacemaker
     shell: "echo Checking Master HA parameters with pacemaker"
     notify:
       - Verify openshift_master_cluster_method
       - Verify openshift_master_cluster_password
       - Verify openshift_master_cluster_vip
       - Verify openshift_master_cluster_public_vip
       - Verify openshift_master_cluster_hostname
       - Verify openshift_master_cluster_public_hostname
     when: "{{master_count}} > 1 and (groups[g_lb]|length)==0"
     tags: add_host
   
   - name: Check Master HA parameters with lb
     shell: "echo Checking Master HA parameters with lb"
     notify:
       - Verify openshift_master_cluster_method
       - Verify openshift_master_cluster_hostname
       - Verify openshift_master_cluster_hostname is same as lb hostname
       - Verify openshift_master_cluster_public_hostname
       - Verify openshift_master_cluster_public_hostname is same as lb hostname
     when: "{{master_count}} > 1 and (groups[g_lb]|length) >0"
     tags: add_host

   - name: Check Subscription_manager parameters (it is depending on what you use Subscription_manager or internal_repo)
     shell: "echo Checking Subscription_manager parameters"
     notify:
       - Verify subscription_register_name
       - Verify subscription_register_password
     when: "{{internal_repo_install}} == false and {{internet_connected}} == false and {{subscription_register}} == false"
     tags: add_host
 
   - name: Check if rhel iso file exist on local
     local_action: file path={{ hostvars[groups.oo_ose3_install.0].internal_repo_iso_src_path}}/{{ hostvars[groups.oo_ose3_install.0].internal_repo_rhel_iso_long}}
     tags: add_host

   - name: Check if ose iso file exist on local
     local_action: file path={{ hostvars[groups.oo_ose3_install.0].internal_repo_iso_src_path}}/{{ hostvars[groups.oo_ose3_install.0].internal_repo_ose_iso_long}}
     tags: add_host

   handlers:
    - name : Verify dns_wildcard_domain
      fail:
        msg="dns_wildcard_domain is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].dns_wildcard_domain}}' is not defined"
      tags: add_host

    - name : Verify dns_routers_ip
      fail:
         msg="dns_routers_ip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].dns_routers_ip}}' is not defined"
      tags: add_host

    - name : Verify dns_host_ip
      fail:
         msg="dns_host_ip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].dns_host_ip}}' is not defined"
      tags: add_host

    - name : Verify proxy_vip
      fail:
         msg="proxy_vip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].proxy_vip}}' is not defined"
      tags: add_host

    - name : Verify proxy_host_ip
      fail:
         msg="proxy_host_ip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].proxy_host_ip}}' is not defined"
      tags: add_host

    - name : Verify internal_repo_host_ip
      fail:
         msg="internal_repo_host_ip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].internal_repo_host_ip}}' is not defined"
      tags: add_host


    - name : Verify internal_repo_host_name
      fail:
         msg="internal_repo_host_name is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].internal_repo_host_name}}' is not defined"
      tags: add_host

    - name : Verify nfs_iscsi_host_ip
      fail:
         msg="nfs_iscsi_host_ip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].nfs_iscsi_host_ip}}' is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_password
      fail:
         msg="openshift_master_cluster_password is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_password}}' is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_vip
      fail:
         msg="openshift_master_cluster_vip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_vip}}' is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_public_vip
      fail:
         msg="openshift_master_cluster_public_vip is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_public_vip}}' is not defined"
      tags: add_host


    - name : Verify openshift_master_cluster_hostname
      fail:
         msg="openshift_master_cluster_hostname is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_hostname}}' is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_method
      fail:
         msg="openshift_master_cluster_method is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_method}}' is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_public_hostname
      fail:
         msg="openshift_master_cluster_public_hostname is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_public_hostname}}' is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_hostname is same as lb hostname
      fail:
         msg="openshift_master_cluster_hostname is not same as lb hostname"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_hostname}}' != '{{groups.oo_lb.0}}'"
      tags: add_host

    - name : Verify openshift_master_cluster_public_hostname is same as lb hostname
      fail:
         msg="openshift_master_cluster_public_hostname is not same as lb hostname"
      when: "'{{hostvars[groups.oo_ose3_install.0].openshift_master_cluster_public_hostname}}' != '{{groups.oo_lb.0}}'"
      tags: add_host

    - name : Verify subscription_register_name
      fail:
         msg="subscription_register_name is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].subscription_register_name}}' is not defined"
      tags: add_host

    - name : Verify subscription_register_password
      fail:
         msg="subscription_register_password is not undefinded"
      when: "'{{hostvars[groups.oo_ose3_install.0].subscription_register_password}}' is not defined"
      tags: add_host
