 - name: Populate config host groups
   hosts: localhost
   gather_facts: no
  
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
 
   tasks:
   - name: Evaluate oo_ose3_install_to_config
     add_host:
       name: "{{ item }}"
       groups: "oo_ose3_install"
     with_items: "{{ groups[g_ose3_install_group] | default([]) }}"
     tags: add_host

   - name: Evaluate oo_masters_to_config
     add_host:
       name: "{{ item }}"
       groups: oo_masters
       ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
       ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: "{{ groups[g_masters_group] | default([]) }}"
     tags: add_host
   
   - name: Evaluate oo_nodes_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_nodes
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: "{{ groups[g_nodes_group] }}"
     tags: add_host
 
   - name: Evaluate oo_etcds_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_etcds
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: "{{ groups[g_etcds_group]|default([]) }}"
     tags: add_host
 
   - name: Evaluate oo_lb_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_lb
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: "{{ groups[g_lb]|default([]) }}"
     when: "{{groups[g_lb] is defined}}"
     tags: add_host

   - name: Evaluate oo_infra_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_infra
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: "{{ groups[g_infra] }}"
     tags: add_host

#Check conditions(To-Do vm network setting verification)
 - include: ./checking_conditions.yaml
 - include: ../ose3-infra/config.yaml
 - include: ../ose3-master/config.yaml
 - include: ../ose3-lb/config.yaml
 - include: ../ose3-etcd/config.yaml
 - include: ../ose3-node/config.yaml
 - include: ./ose3_install_prerequites_common.yaml
 - include: ./ose3_install_prerequites_master.yaml
 #- include: ./ose3_install_prerequites_node.yaml
 #- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
