 - name: Populate config host groups
   hosts: localhost
   gather_facts: no
   tasks:
   - name: Evaluate oo_ose3_install_to_config
     add_host:
       name: "{{ item }}"
       groups: oo_ose3_install
     with_items: groups[g_ose3_install_group] | default([])
     tags: add_host

   - name: Evaluate oo_masters_to_config
     add_host:
       name: "{{ item }}"
       groups: oo_masters
       ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
       ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: groups[g_masters_group] | default([])
     tags: add_host
   
   - name: Evaluate oo_nodes_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_nodes
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: groups[g_nodes_group]
     tags: add_host
 
   - name: Evaluate oo_etcds_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_etcds
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: groups[g_etcds_group]
     tags: add_host
   
   - name: Evaluate oo_infra_to_config
     add_host:
      name: "{{ item }}"
      groups: oo_infra
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_sudo: "{{ g_sudo | default(omit) }}"
     with_items: groups[g_infra]
     tags: add_host

#Check conditions
   - name: Verify if it gets enough information for selected options(dns/proxy/internal_repo) 
     set_fact:
       internet_connected: "{{ hostvars[groups.oo_ose3_install.0].internet_connected }}"
       dns_install: "{{ hostvars[groups.oo_ose3_install.0].dns_install }}"
       proxy_install: "{{ hostvars[groups.oo_ose3_install.0].proxy_install }}"
       internal_repo_install: "{{ hostvars[groups.oo_ose3_install.0].internal_repo_install }}"
       nfs_iscsi_install: "{{ hostvars[groups.oo_ose3_install.0].nfs_iscsi_install }}"
       master_count: "{{ (groups[g_masters_group] | length) }}"
       subscription_register: "{{ (hostvars[groups.oo_ose3_install.0].subscription_register) }}"
     tags: add_host

   - name: Check DNS parameters
     shell: "echo Checking DNS parameters"
     notify:
       - Verify dns_wildcard_domain
       - Verify dns_routers_ip
       - Verify dns_host_ip
     when: "{{dns_install}} == true"
     tags: add_host
  
   - name: Check Proxy parameters
     shell: "echo Checking Proxy parameters"
     notify:
       - Verify proxy_vip
       - Verify proxy_host_ip
     when: "{{proxy_install}} == true"
     tags: add_host

   - name: Check Internal_repo parameters
     shell: "echo Checking Internal_repo parameters"
     notify:
       - Verify internal_repo_host_ip
       - Verify internal_repo_host_name
     when: "{{internal_repo_install}} == true"
     tags: add_host

   - name: Check NFS  parameters
     shell: "echo Checking NFS parameters"
     notify:
       - Verify nfs_iscsi_host_ip
     when: "{{nfs_iscsi_install}} == true"
     tags: add_host

   - name: Check Master HA parameters
     shell: "echo Checking Master HA parameters"
     notify:
       - Verify openshift_master_cluster_password
       - Verify openshift_master_cluster_vip
       - Verify openshift_master_cluster_public_vip
       - Verify openshift_master_cluster_hostname
       - Verify openshift_master_cluster_public_hostname
     when: "{{master_count}} > 1"
     tags: add_host

   - name: Check Subscription_manager parameters (it is depending on what you use Subscription_manager or internal_repo)
     shell: "echo Checking Subscription_manager parameters"
     notify:
       - Verify subscription_register_name
       - Verify subscription_register_password
     when: "{{internal_repo_install}} == false and {{internet_connected}} == false and {{subscription_register}} == false"
     tags: add_host


   handlers:
    - name : Verify dns_wildcard_domain
      fail:
        msg="dns_wildcard_domain is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].dns_wildcard_domain is not defined"
      tags: add_host
  
    - name : Verify dns_routers_ip
      fail:
         msg="dns_routers_ip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].dns_routers_ip is not defined"
      tags: add_host

    - name : Verify dns_host_ip
      fail:
         msg="dns_host_ip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].dns_host_ip is not defined"
      tags: add_host

    - name : Verify proxy_vip
      fail:
         msg="proxy_vip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].proxy_vip is not defined"
      tags: add_host
   
    - name : Verify proxy_host_ip
      fail:
         msg="proxy_host_ip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].proxy_host_ip is not defined"
      tags: add_host

    - name : Verify internal_repo_host_ip
      fail:
         msg="internal_repo_host_ip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].internal_repo_host_ip is not defined"
      tags: add_host
 
     
    - name : Verify internal_repo_host_name
      fail:
         msg="internal_repo_host_name is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].internal_repo_host_name is not defined"
      tags: add_host

    - name : Verify nfs_iscsi_host_ip
      fail:
         msg="nfs_iscsi_host_ip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].nfs_iscsi_host_ip is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_password
      fail:
         msg="openshift_master_cluster_password is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].openshift_master_cluster_password is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_vip
      fail:
         msg="openshift_master_cluster_vip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].openshift_master_cluster_vip is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_public_vip
      fail:
         msg="openshift_master_cluster_public_vip is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].openshift_master_cluster_public_vip is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_hostname
      fail:
         msg="openshift_master_cluster_hostname is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].openshift_master_cluster_hostname is not defined"
      tags: add_host

    - name : Verify openshift_master_cluster_public_hostname
      fail:
         msg="openshift_master_cluster_public_hostname is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].openshift_master_cluster_public_hostname is not defined"
      tags: add_host

    - name : Verify subscription_register_name
      fail:
         msg="subscription_register_name is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].subscription_register_name is not defined"
      tags: add_host

    - name : Verify subscription_register_password
      fail:
         msg="subscription_register_password is not undefinded"
      when: "hostvars[groups.oo_ose3_install.0].subscription_register_password is not defined"
      tags: add_host

    #To-Do vm network setting verification
