
#This file set up prerequites process for installation of ose3

  - name: Prerequites process for nodes.
    hosts: nodes
    gather_facts: no

    tasks:
    - name: Install nessasary packages
      shell: "yum install -y  net-tools bind-utils iptables-services bridge-utils bash-completion"
      tags: openshift_ansible
