
#This file set up prerequites process for installation of ose3

  - name: Prerequites process for masters.
    hosts: masters
    gather_facts: no

    tasks:
    - name: Install nessasary packages
      shell: "yum install -y atomic-openshift-utils"
      tags: openshift_ansible
