
#This file set up prerequites process for installation of ose3

  - name: Prerequites process for masters:nodes:etcd:lb.
    hosts: masters:nodes:etcd:lb
    gather_facts: no

    pre_tasks:
    - name: Install nessasary packages
      shell: "yum install -y  docker"
      tags: openshift_ansible
    
    roles:
    - { role: ose_docker_configure,  tags: openshift_ansible}
