
 - name: Set up masters machine
   hosts: masters
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd
     tags: pre_tasks

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
        development_mode: "{{hostvars[groups.oo_ose3_install.0].development}}"
        internet_connected: "{{hostvars[groups.oo_ose3_install.0].internet_connected}}"
     tags: pre_tasks

   roles:
    - { role: ose_hosts_file, tags: master, hosts}
    - { role: ose_network_configure, when: development_mode == "true", tags: master, network} 
    - { role: update_yum_repo, when: "{{hostvars[groups.oo_ose3_install.0].internal_repo_install}} == true", tags: master, yum_repo } 
    - { role: update_resolv_conf, tags: master, resolv_conf}
    - { role: subscription_register, when: "{{subscription_register}} == true and {{hostvars[groups.oo_ose3_install.0].internal_repo_install}} == false", tags: master, scription_register} 
    - { role: ose_ansible_installer,  tags: master, openshift_ansible}
