
    - name: Gather service ip of docker registry
      shell: oc get svc|grep docker-registry|awk '{print $2}'
      register: docker_registry_svc_ip

    - debug: var={{docker_registry_svc_ip.stdout == "" }}

    - name: Create script for docker registry 
      template: src="create_registry.sh.j2" dest="/root/ose/create_registry.sh" mode=0777
      delegate_to: "{{master_ip}}"
      when: docker_registry_svc_ip.stdout == "" 

    - name: Execute the script to create docker registry 
      shell: /root/ose/create_registry.sh 
      delegate_to: "{{master_ip}}"
      when: docker_registry_svc_ip.stdout == "" 
      register: created_registry
    

    - name: Execute the script to attach nfs volume to docker registry 
      template: src="attach_vol_to_registry.sh.j2" dest="/root/ose/attach_vol_to_registry.sh" mode=0777
      delegate_to: "{{master_ip}}"
      when: "{{attach_vol_to_registry}} == true"

    - name: Execute the script to attach nfs volume to docker registry 
      shell: /root/ose/attach_vol_to_registry.sh
      delegate_to: "{{master_ip}}"
      when: "{{attach_vol_to_registry}} == true"

    - name: Gather service ip of docker registry
      shell: oc get svc|grep docker-registry|awk '{print $2}'
      register: docker_registry_svc_ip
