

  - name: "mount rhel iso file to {{apache_repo_path}}/{{internal_repo_rhel_iso_short}}"
    mount: src={{iso_dest_path}}/{{internal_repo_rhel_iso_long}}  name={{apache_repo_path}}/{{internal_repo_rhel_iso_short}} fstype="iso9660" opts="loop" state=mounted

  - name: Copy repo file under yum.repos.d
    template: src=local.repo.j2 dest=/etc/yum.repos.d/local.repo
 
  - name: clean yum repo
    shell: yum clean all
