
  - name: Check if there is already added to hosts
    shell: "grep -ir '{{groups.oo_masters.0}}' /etc/hosts"
    ignore_errors: yes
    register: check_hosts_file

  - name: generate hosts file
    action: template src=hosts.j2 dest=/tmp/hosts.ose3
    when: "check_hosts_file.rc == 1"

  - name: add ose3 hosts to previous hosts file
    shell: "cat /tmp/hosts.ose3 >> /etc/hosts"
    when: "check_hosts_file.rc == 1"
