
 - name: Set up lb machine
   hosts: lb
   gather_facts: false

   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd
     tags: pre_tasks

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
        development_mode: "{{hostvars[groups.oo_ose3_install.0].development}}"
        internet_connected: "{{hostvars[groups.oo_ose3_install.0].internet_connected}}"
        temp_path: "/root/tmp"
     tags: pre_tasks

   roles:
    - { role: ose_hosts_file, tags: hosts}
    - { role: ose_network_configure, when: development_mode == "true", tags: network}
    - { role: update_yum_repo, when: "{{hostvars[groups.oo_ose3_install.0].internal_repo_install}} == true", tags: yum_repo }
    - { role: update_resolv_conf, tags: resolv_conf}
    - { role: subscription_register, when: "{{subscription_register}} == true and {{hostvars[groups.oo_ose3_install.0].internal_repo_install}} == false", tags: subscription_register}
