
 - name: Change login page logo 
   hosts: masters
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd
     tags: pre_tasks

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
        output_img_name: fb-resized.png
     tags: pre_tasks

   roles:
      # default values - input_img: input.png, output_img: output.png, size: 193x44
      # example - { role: resize_image, input_img: "/etc/origin/master/stylesheet/images/ctc-long.png", output_img: "ctc-long-resized.png", size: "193x44" }
      - { role: resize_image, input_img: "/etc/origin/master/stylesheet/images/BCBS_Florida.png", output_img: "{{output_img_name}}", size: "193x44" }
      - { role: configure_login_logo, resized_img: "{{output_img_name}}", master_url: "lb.example.com:8443", login_html_folder: "/etc/origin/master" }
