
 - name: Test for each role
   hosts: infra
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd
     tags: pre_tasks

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
        development_mode: "{{hostvars[groups.oo_ose3_install.0].development}}"
        internet_connected: "{{hostvars[groups.oo_ose3_install.0].internet_connected}}"
        internal_repo_install: "{{hostvars[groups.oo_ose3_install.0].internal_repo_install}}"
        subscription_register: "{{hostvars[groups.oo_ose3_install.0].subscription_register}}"
        iso_dest_path: "{{hostvars[groups.oo_ose3_install.0].internal_repo_iso_src_path}}"
        temp_path: "/root/tmp"
        internal_repo_apache_repo_path: "{{hostvars[groups.oo_ose3_install.0].internal_repo_apache_repo_path}}"
     tags: pre_tasks

   - debug: msg="{{internal_repo_install}} == true and {{internal_repo_mounted.results[0].stdout}} == 0 and {{internal_repo_mounted.results[1].stdout}} == 0"

