
 - name: Set up infra machine
   hosts: infra
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
        development_mode: "{{hostvars[groups.oo_ose3_install.0].development}}"
 
   roles:
    - { role: ose_hosts_file, tag: infra }
    - { role: ose_network_configure, when: development_mode == "true", tag: infra } 
