
 - name: Set up infra machine
   hosts: infra
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd
     tags: pre_tasks

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
        development_mode: "{{hostvars[groups.oo_ose3_install.0].development}}"
        internet_connected: "{{hostvars[groups.oo_ose3_install.0].internet_connected}}"
        internal_repo_install: "{{hostvars[groups.oo_ose3_install.0].internal_repo_install}}"
        subscription_register: "{{hostvars[groups.oo_ose3_install.0].subscription_register}}"
        iso_dest_path: "{{hostvars[groups.oo_ose3_install.0].internal_repo_iso_src_path}}"
        temp_path: "/root/tmp"
        internal_repo_apache_repo_path: "{{hostvars[groups.oo_ose3_install.0].internal_repo_apache_repo_path}}"
     tags: pre_tasks


   - name: create temp folder for intallation
     file: path="{{iso_dest_path}}" state="directory" force="false"
     when: 'internal_repo_install == "true" or subscription_register == "false"'
     tags: infra
   
   - name: check if the iso files exist
     shell: "ls {{iso_dest_path}}/{{item}} |wc -l"
     with_items:
       - "{{internal_repo_rhel_iso_long}}"
       - "{{internal_repo_ose_iso_long}}"
     ignore_errors: yes
     when: 'internal_repo_install == "true" or subscription_register == "false"'
     register: iso_exist_int
     tags: infra

   - name: check if the internal repos are mounted
     shell: "ls {{internal_repo_apache_repo_path}}/{{item}} |wc -l"
     with_items:
       - "{{internal_repo_rhel_iso_short}}"
       - "{{internal_repo_ose_iso_short}}"
     ignore_errors: yes
     when: 'internal_repo_install == "true" or subscription_register == "false"'
     register: internal_repo_mounted
     tags: infra

   - name: copy iso files
     copy: src="{{internal_repo_iso_src_path}}/{{item}}" dest="{{iso_dest_path}}/{{item}}" force="no"
     with_items:
       - "{{internal_repo_rhel_iso_long}}"
       - "{{internal_repo_ose_iso_long}}"
     when: 'internal_repo_install == "true" and iso_exist_int.results[0].stdout == "0" and iso_exist_int.results[1].stdout == "0"'
     tags: infra
   
   roles:
    - { role: ose_hosts_file, tags: infra, hosts}
    - { role: ose_network_configure, when: development_mode == "true", tags: infra, network} 
    - { role: subscription_register, when: subscription_register == "true", tags: infra, temp_repo}
    - { role: temp_repo_with_iso, when: 'internal_repo_install == "true" or subscription_register == "false"', tags: infra, temp_repo}
    - { role: ose_dns_configure, tags: infra, dns} 
    - { role: update_resolv_conf, tags: infra, resolv_conf} 
    - { role: internal_repo_with_apache, when: 'internal_repo_install == "true" and internal_repo_mounted.results[0].stdout == "0" and internal_repo_mounted.results[1].stdout == "0"', tags: infra, internal_repo } 
    - { role: update_yum_repo, when: 'internal_repo_install == "true" or subscription_register == "false"', tags: infra, yum_repo } 
