
 - name: Set up infra machine
   hosts: infra
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
 
   roles:
    - { role: ose_hosts_file }
