
  - name: Set up docker configuration - storage
    action: template src="docker-storage-setup.j2"  dest="/etc/sysconfig/docker-storage-setup"
    when: "{{hostvars[groups.oo_ose3_install.0].docker_setup}} == true and hostvars[groups.oo_ose3_install.0].docker_storage_block_dev_name is defined"
    tags: docker_config
 
  - name: Execute docker-storage-setup
    command: docker-storage-setup  
    ignore_errors: yes
    when: "{{hostvars[groups.oo_ose3_install.0].docker_setup}} == true and hostvars[groups.oo_ose3_install.0].docker_storage_block_dev_name is defined"
    tags: docker_config

  - name: Check docker option is exist 
    shell: "grep '172.30.0.0' /etc/sysconfig/docker|grep -v ^#|wc -l"
    register: docker_option_exist
 
  - name: Update docker options
    lineinfile:
      dest=/etc/sysconfig/docker
      state=present
      regexp="^OPTIONS=\'--selinux-enabled"
      insertafter="^OPTIONS"
      line="OPTIONS=\'--selinux-enabled --insecure-registry 172.30.0.0/16\'"
    when: docker_option_exist.stdout == "0"
    tags: docker_config
  
