

   - name: subscription register if you have rhn id.
     redhat_subscription: state=present username={{subscription_register_id}} password={{subscription_register_password}}  pool='{{subscription_register_password}}'
     when: "{{subscription_register}} == true"
