

   - name: subscription register if you have rhn id.
     redhat_subscription: state=present username={{subscription_register_id}} password={{subscription_register_password}}  pool='{{subscription_register_pool_id}}'
     when: "{{subscription_register}} == true"
   
   - name: copy enable_ose_repos.sh
     template: src="enable_ose_repos.sh.j2" dest="/root/enable_ose_repos.sh" mode=0775
     when: "{{subscription_register}} == true"

   - name: enable ose repos
     shell: /root/enable_ose_repos.sh
     when: "{{subscription_register}} == true"

