

   - name: Copy resolv.conf
     template: src="resolv.conf.j2" dest="/root/resolv.conf.txt"
     tags: resolv_config
  
   - name: add infra dns 
     shell: cat /root/resolve.conf.txt >> /etc/resolve.conf

   - name: clean temp file
     file: path=/root/resolv.conf.txt  state=absent
