
 - name: Test for each role
   hosts: infra
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd
     tags: pre_tasks

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"
     tags: pre_tasks

   roles:
    - { role: ose_nfs, nfs_registry_path: /exports/nfs/registry}
