
  - name: test
    shell: yum repolist

  - name: install httpd server
    yum: name=httpd state=installed 

  - name: Create rhel/ose repo folder
    file: path={{internal_repo_apache_repo_path}}/{{item}} state=directory force=false
    with_items:
       - "{{internal_repo_rhel_iso_short}}"
       - "{{internal_repo_ose_iso_short}}"
  
  - name: mount rhel/ose iso file to {{apache_repo_path}}
    mount: src={{iso_dest_path}}/{{item.long}}  name={{internal_repo_apache_repo_path}}/{{item.short}} fstype="iso9660" opts="loop" state=mounted
    with_items:
     - { long: '{{internal_repo_rhel_iso_long}}', short: '{{internal_repo_rhel_iso_short}}'}
     - { long: '{{internal_repo_ose_iso_long}}', short: '{{internal_repo_ose_iso_short}}'}
  
  - name: Start httpd server & enable to chkconfig
    service: name=httpd state=started enabled=yes

  - name: Stop firewalld 
    service: name=firewalld state=stopped enabled=no
  
  - name: Disable selinux
    selinux: state=disabled
